name: Publish Docker

# Controls when the workflow will run
on:
  push:
    branches: [main]

  # allows triggering the workflow manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: uclatall/deepnote
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          snapshot: true
          default_branch: main
